models.py
###################
# Добавить ТЭГ в БД
#   from app import db
#   from models import Tag
#   tag = Tag(name='python')
#   db.session.add(tag) //добавить в сессию
#   db.session.commit() //запись в БД
#
#
#
#
#
#
#







from app import db
from datetime import datetime
# regular expression lib
import re


# класс отвечает за хранение постов
def slugify(s):
    # \w+ - все буквы и цифры и _
    # ^ - не
    pattern = r'[^\w+]'
    # sub - substitution, замена(что заменять, на что заменять, где ищем)
    return re.sub(pattern, '-', s).lower()


class Post(db.Model):
    # id это колонка(хранит int, первичный ключ)
    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(140))
    # slug - это ЧПУ - человеко-понятный url, url - уникален
    slug = db.Column(db.String(140), unique=True)
    body = db.Column(db.Text)
    created = db.Column(db.DateTime, default=datetime.now())

    # *args - позиционные аргум.(список) **kwargs - именованные аргум.(словарь key-word)
    def __init__(self, *args, **kwargs):
        # вызвать конструктор предка(SQLAlchemy.Model)
        # супер класс класса Post, self - ссылка на экземпляр конкретного класса
        super(Post, self).__init__(*args, **kwargs)
        self.generate_slug()

    def generate_slug(self):
        if self.title:
            self.slug = slugify(self.title)

    # representation(представление при выводе на экран(аналог toString))
    def __repr__(self):
        return '<Post id: {0}, title: {1}>'.format(self.id, self.title)


class Tag(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(100))
    slug = db.Column(db.String(100))

    def __init__(self, *args, **kwargs):
        super(Tag, self).__init__(*args, **kwargs)
        self.slug = slugify(self.name)

    def __repr__(self):
        return '<Tag id: {}, name: {}>'.format(self.id, self.name)

app.py
#приложение
from flask import Flask
from config import Configuration
from flask_sqlalchemy import SQLAlchemy

from flask_migrate import Migrate, MigrateCommand
from flask_script import Manager

app = Flask(__name__)
app.config.from_object(Configuration)

db = SQLAlchemy(app)

# app и db потому что миграция выстраивает корреляцию межлу текущей версией приложения и базы данных
migrate = Migrate(app, db)

manager = Manager(app)
# 1-название команды, 2-что за комманда
manager.add_command('db', MigrateCommand)

main.py
#точка входа
from app import app
#чтобы Flask знал что есть вьюха
import view
from posts.blueprint import posts

app.register_blueprint(posts, url_prefix='/blog')
app.run()

posts/blueprint.py
from flask import Blueprint
from flask import render_template
from models import Post
# 1 - название blueprint'a
# 3 - все шаблоны хранятся в папке templates -> posts (пусть не смущает posts\templates\posts это от дублирования имен как и в Django)
# для того чтобы зарегать blueprint надо импортировать posts в app.py
posts = Blueprint('posts', __name__, template_folder='templates')

# вроде бы обращаемся к корню но мы зарегали blueprint по url_prefix='/blog' и получается url = /blog/
@posts.route('/')
def index():
    posts = Post.query.all()
    return render_template('posts/index.html', posts=posts)

#<имя параметра>
@posts.route('/<slug>')
# здесь тоже что и в <>, т.е slug
def post_detail(slug):
    post = Post.query.filter(Post.slug == slug).first()
    return render_template('posts/post_detail.html', post=post)

posts/templates/posts/index.html
{% extends 'base.html' %}

{% block title %}
    Blueprint Index Page 
{% endblock  %}

{% block content_title %}
    Posts
{% endblock  %}

{% block content %}
    <br>
    <br>
    <ul>
        {% for post in posts  %}
            <li>
                                                                <!-- slug(url_for), post из for -->
                <b>Title => </b><a href="{{ url_for('posts.post_detail', slug=post.slug) }}">{{post.title}}</a><b> Date => </b>{{ post.created}} 
            </li>
        {% endfor %}
    </ul>
{% endblock  %}

posts/templates/posts/post_detail.html
{% extends 'base.html' %}

 {% block title %}
    {{post.title}}
 {% endblock %}

 {% block content_title %}
    {{post.title}}
 {% endblock  %}

 {% block content %}
    {{post.body}}
 {% endblock  %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=1, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>

        {% block title %}
        {% endblock %}
    </title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!-- <link href="https://fonts.googleapis.com/css?family=Barriecito&display=swap" rel="stylesheet"> -->
    <!-- <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}"> -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Tangerine">


    <style>
        #content_title {
            font-family: 'Tangerine', serif;
            font-size: 48px;
        }
    </style>
</head>

<body>
    <!-- Bootstrap Navbar (https://getbootstrap.com/docs/4.3/components/navbar/) -->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href=" {{url_for('index')}} ">Flask</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{{url_for('posts.index')}}">Blog <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Link</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Dropdown
                        </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="#">Action</a>
                        <a class="dropdown-item" href="#">Another action</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                    </div>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
                </li>
            </ul>
            <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
        </div>
    </nav>
    <div class="container">
        <div class="row">
            <h1>
                {% block content_title %}
                {% endblock %}
            </h1>
        </div>
        {% block content %} 
        {% endblock %}
    </div>
</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block title %}
    Index Page
{% endblock %}

{% block content_title %}
    <div id="content_title">
        Hello, {{name}}
    </div>
{% endblock %}

{% block content %}
    Lorem ipsum dolor sit amet consectetur adipisicing elit. Cum laudantium quasi nam est sint. At, culpa aliquid. Magni ratione qui dolorem, quasi nostrum corrupti error, laudantium, sed modi cumque quibusdam! Lorem ipsum
    dolor, sit amet consectetur adipisicing elit. Molestiae labore iure quas consectetur voluptatum perferendis, porro sit dolorem, id aspernatur eligendi! Sunt iure maiores laudantium tempora velit quos veritatis cupiditate! Lorem ipsum dolor sit amet consectetur
    adipisicing elit. Quod enim nemo maiores nam nostrum vel adipisci suscipit. Quam quaerat maiores, nostrum assumenda pariatur corrupti, aspernatur, vitae dolores sed et saepe! Lorem ipsum dolor sit amet consectetur adipisicing elit. Inventore ducimus necessitatibus
    natus eveniet architecto sed quisquam vero voluptates numquam eligendi tempora aperiam, optio harum quia sequi? Maiores cum quidem omnis.
{% endblock %}